[package]
name = "lsl-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_plot = "0.32.1"
lsl = { git = "https://github.com/labstreaminglayer/liblsl-rust" }
crossbeam-channel = "0.5"
ndarray = "0.16.1"
